apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service-svc
  labels:
    app: shoppingcartservice
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: shoppingcartservice
