kube-prometheus-stack:
  nameOverride: 'monitoring'
  alertmanager:
    enabled: false
  grafana:
    enabled: false

prometheus-adapter:
  prometheus:
    url: http://{{ .Release.Name }}-monitoring-prometheus.{{ .Release.Namespace }}.svc
  rules:
    default: false
    custom:
    - seriesQuery: '{__name__=~"^local_drone_control_.*"}'
      resources:
        overrides:
          pod: { resource: "pod" }
          namespace: { resource: "namespace" }
      metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'

