apiVersion: v1
kind: Service
metadata:
  name: restaurant-drone-deliveries-service-svc
spec:
  selector:
    app: restaurant-drone-deliveries-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
