apiVersion: v1
kind: Service
metadata:
  name: local-drone-control-service-svc
spec:
  selector:
    app: local-drone-control-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
