
#create-table-mssql
IF NOT EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'"AKKA_PROJECTION_OFFSET_STORE"') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE "AKKA_PROJECTION_OFFSET_STORE" (
  "PROJECTION_NAME" VARCHAR(255) NOT NULL,
  "PROJECTION_KEY" VARCHAR(255) NOT NULL,
  "CURRENT_OFFSET" VARCHAR(255) NOT NULL,
  "MANIFEST" VARCHAR(4) NOT NULL,
  "MERGEABLE" BIT NOT NULL,
  "LAST_UPDATED" BIGINT NOT NULL
)

ALTER TABLE "AKKA_PROJECTION_OFFSET_STORE" ADD CONSTRAINT "PK_PROJECTION_ID" PRIMARY KEY("PROJECTION_NAME","PROJECTION_KEY")

CREATE INDEX "PROJECTION_NAME_INDEX" ON "AKKA_PROJECTION_OFFSET_STORE" ("PROJECTION_NAME")
END
#create-table-mssql
