
#create-table-mysql
create table if not exists AKKA_PROJECTION_OFFSET_STORE (
  PROJECTION_NAME VARCHAR(255) NOT NULL,
  PROJECTION_KEY VARCHAR(255) NOT NULL,
  OFFSET VARCHAR(255) NOT NULL,
  MANIFEST VARCHAR(4) NOT NULL,
  MERGEABLE BOOLEAN NOT NULL,
  LAST_UPDATED TEXT NOT NULL
);

create index PROJECTION_NAME_INDEX on AKKA_PROJECTION_OFFSET_STORE (PROJECTION_NAME);

alter table AKKA_PROJECTION_OFFSET_STORE
  add constraint PK_PROJECTION_ID primary key(PROJECTION_NAME,PROJECTION_KEY);
#create-table-mysql
