
#create-table-default
create table if not exists "AKKA_PROJECTION_OFFSET_STORE" (
  "PROJECTION_NAME" VARCHAR(255) NOT NULL,
  "PROJECTION_KEY" VARCHAR(255) NOT NULL,
  "OFFSET" VARCHAR(255) NOT NULL,
  "MANIFEST" VARCHAR(4) NOT NULL,
  "MERGEABLE" BOOLEAN NOT NULL,
  "LAST_UPDATED" TIMESTAMP(9) WITH TIME ZONE NOT NULL
);

create index "PROJECTION_NAME_INDEX" on "AKKA_PROJECTION_OFFSET_STORE" ("PROJECTION_NAME");

alter table "AKKA_PROJECTION_OFFSET_STORE"
  add constraint "PK_PROJECTION_ID" primary key("PROJECTION_NAME","PROJECTION_KEY");
#create-table-default

#create-table-mysql
create table if not exists AKKA_PROJECTION_OFFSET_STORE (
  PROJECTION_NAME VARCHAR(255) NOT NULL,
  PROJECTION_KEY VARCHAR(255) NOT NULL,
  OFFSET VARCHAR(255) NOT NULL,
  MANIFEST VARCHAR(4) NOT NULL,
  MERGEABLE BOOLEAN NOT NULL,
  LAST_UPDATED TEXT NOT NULL
);

create index PROJECTION_NAME_INDEX on AKKA_PROJECTION_OFFSET_STORE (PROJECTION_NAME);

alter table AKKA_PROJECTION_OFFSET_STORE
  add constraint PK_PROJECTION_ID primary key(PROJECTION_NAME,PROJECTION_KEY);
#create-table-mysql

#create-table-mssql
IF  NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'AKKA_PROJECTION_OFFSET_STORE') AND type in (N'U'))
begin
create table "AKKA_PROJECTION_OFFSET_STORE" (
  "PROJECTION_NAME" VARCHAR(255) NOT NULL,
  "PROJECTION_KEY" VARCHAR(255) NOT NULL,
  "OFFSET" VARCHAR(255) NOT NULL,
  "MANIFEST" VARCHAR(4) NOT NULL,
  "MERGEABLE" BIT NOT NULL,
  "LAST_UPDATED" DATETIME2 NOT NULL
)

alter table "AKKA_PROJECTION_OFFSET_STORE" add constraint "PK_PROJECTION_ID" primary key("PROJECTION_NAME","PROJECTION_KEY")

create index "PROJECTION_NAME_INDEX" on "AKKA_PROJECTION_OFFSET_STORE" ("PROJECTION_NAME")
end
#create-table-mssql

#create-table-oracle
BEGIN
execute immediate 'create table "AKKA_PROJECTION_OFFSET_STORE" ("PROJECTION_NAME" VARCHAR2(255) NOT NULL,"PROJECTION_KEY" VARCHAR2(255) NOT NULL,"OFFSET" VARCHAR2(255) NOT NULL,"MANIFEST" VARCHAR2(4) NOT NULL,"MERGEABLE" CHAR(1) NOT NULL check ("MERGEABLE" in (0, 1)),"LAST_UPDATED" TIMESTAMP(9) WITH TIME ZONE NOT NULL) ';
execute immediate 'alter table "AKKA_PROJECTION_OFFSET_STORE" add constraint "PK_PROJECTION_ID" primary key("PROJECTION_NAME","PROJECTION_KEY") ';
execute immediate 'create index "PROJECTION_NAME_INDEX" on "AKKA_PROJECTION_OFFSET_STORE" ("PROJECTION_NAME") ';
EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
        NULL; -- suppresses ORA-00955 exception
      ELSE
         RAISE;
      END IF;
END;
#create-table-oracle