apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: local-drone-control
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: local-drone-control
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: local_drone_control_active_entities
      target:
        type: Value
        averageValue: 100
