apiVersion: v1
kind: Service
metadata:
  name: local-drone-control
  labels:
    app: local-drone-control
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: local-drone-control
