apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: local-drone-control
spec:
  recommenders:
  - name: custom
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: local-drone-control
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 2
  resourcePolicy:
    containerPolicies:
      - containerName: local-drone-control
        mode: "Auto"
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 1000m
          memory: 1024Mi
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits
