name: Integration Tests for gRPC

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

permissions:
  contents: read

jobs:
  test:
    name: Build and Test Integration for gRPC
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jdkVersion: "1.8.0",  jvmName: "temurin:1.8.0",  extraOpts: '' }
          - { jdkVersion: "1.11.0", jvmName: "temurin:1.11.0", extraOpts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
          - { jdkVersion: "1.17.0", jvmName: "temurin:1.17.0", extraOpts: '' }

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v3.3.0
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.3
        uses: coursier/cache-action@d1039466d0812d6370649b9afb02bbf5f646bacf

      - name: Set up JDK ${{ matrix.jdkVersion }}
        # https://github.com/coursier/setup-action/releases
        # v1.3.0
        uses: coursier/setup-action@70323223454ac2a9eb2de46f389b4d045cbcdea5
        with:
          jvm: ${{ matrix.jvmName }}

      - name: Run all integration tests with default Scala and Java ${{ matrix.jdkVersion }}
        run: sbt "akka-projection-grpc-test/It/test" ${{ matrix.extraOpts }}
        env: # Disable Ryuk resource reaper since we always spin up fresh VMs
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
