name: Integration Tests for Slick

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  test:
    name: Build and Test Integration for Slick
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jdkVersion: "1.8.0",  jvmName: "temurin:1.8.0",  extraOpts: '' }
          - { jdkVersion: "1.11.0", jvmName: "temurin:1.11.0", extraOpts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
          - { jdkVersion: "1.17.0", jvmName: "temurin:1.17.0", extraOpts: '' }
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Copy license acceptance
        run: |-
          cp container-license-acceptance.txt akka-projection-slick/src/it/resources/container-license-acceptance.txt

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK ${{ matrix.jdkVersion }}
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: ${{ matrix.jvmName }}

      - name: Run all integration tests with default Scala and Java ${{ matrix.jdkVersion }}
        run: sbt "akka-projection-slick/It/test" ${{ matrix.extraOpts }}
        env: # Disable Ryuk resource reaper since we always spin up fresh VMs
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
