name: Integration Tests for Kafka

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

permissions:
  contents: read

jobs:
  test:
    name: Build and Test Integration for Kafka
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jdkVersion: "1.11.0", jvmName: "temurin:1.11.0", extraOpts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
          - { jdkVersion: "1.17.0", jvmName: "temurin:1.17.0", extraOpts: '' }
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK ${{ matrix.jdkVersion }}
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: ${{ matrix.jvmName }}

      - name: Run all integration tests with default Scala and Java ${{ matrix.jdkVersion }}
        run: sbt "akka-projection-kafka-integration/test" ${{ matrix.extraOpts }} -Dakka.warn-on-no-license-key=false
        env: # Disable Ryuk resource reaper since we always spin up fresh VMs
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
